### ISSUE TITLE
Some products appear twice on page 1 and 2?

### ISSUE THREAD

**Issue by tmphat1312** [tmphat1312/ise-canteen-management#15]
## On page 1, "Com ga xoi mo" is present
![image](https://github.com/tmphat1312/ise-canteen-management/assets/101187517/f81d544b-44fd-4ed4-a804-a9a29a9afe05)

## On page 2, it is still "Com ga xoi mo" present
![image](https://github.com/tmphat1312/ise-canteen-management/assets/101187517/37b5526f-634c-4f51-bd08-18aec69efbe1)

## 'Com ga xoi mo' is not the only one runs into that scenario.

**Comment by Flashback054** [comment]
Seems like somehow mongoose calls .sort() first then .limit() is applied later. Fix incoming.
